### ISSUE TITLE
File D:\code\fake\src\app\FakeLib\ProcessHelper.fs

### ISSUE THREAD

**Issue by brettrowberry** [Zaid-Ajaj/SAFE-TodoList#2]
I cloned the repo in `C:\dev` and ran `build.cmd RunDevMode`. 

```
Node version:
C:\Program Files\nodejs\node.exe --version
v10.4.0
Yarn version:
npm --version
Running build failed.
Error:
System.Exception: Start of process npm failed. The system cannot find the file specified
   at Fake.ProcessHelper.ExecProcessWithLambdas@103-16.Invoke(String message) in D:\code\fake\src\app\FakeLib\ProcessHelper.fs:line 103
   at Fake.ProcessHelper.ExecProcessWithLambdas(FSharpFunc`2 configProcessStartInfoF, TimeSpan timeOut, Boolean silent, FSharpFunc`2 errorF, FSharpFunc`2 messageF) in D:\code\fake\src\app\FakeLib\ProcessHelper.fs:line 103
   at FSI_0005.Build.run(String cmd, String args, String workingDir)
   at FSI_0005.Build.clo@32-1.Invoke(Unit _arg1)
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in D:\code\fake\src\app\FakeLib\TargetHelper.fs:line 626
```

**Comment by Zaid-Ajaj** [comment]
Hello there @brettrowberry! This exception occurs when FAKE can't run the processs "npm --version". Do you have npm installed? 

> Please note that this repo is quite uotdated: using old fable, old remoting...

**Comment by brettrowberry** [comment]
Yes

C:\dev>node —version
v10.4.0
C:\dev>npm —version
6.1.0
